// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNj4jbDJpFlL8HPYT9RpykrBrqrPwVmc',
    appId: '1:1088495781038:web:c46d9e2d25e94588a3d93f',
    messagingSenderId: '1088495781038',
    projectId: 'prohill-pa',
    authDomain: 'prohill-pa.firebaseapp.com',
    storageBucket: 'prohill-pa.firebasestorage.app',
    measurementId: 'G-DMFVMZSGV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxs5M2X9qyiuhRPZN4B8aayagiZ42PJY',
    appId: '1:1088495781038:android:872c060a201f0069a3d93f',
    messagingSenderId: '1088495781038',
    projectId: 'prohill-pa',
    storageBucket: 'prohill-pa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3XoClCSaOAB4w55NyjvF9jHr9aUEYooo',
    appId: '1:1088495781038:ios:a0a11cd9a31d3990a3d93f',
    messagingSenderId: '1088495781038',
    projectId: 'prohill-pa',
    storageBucket: 'prohill-pa.firebasestorage.app',
    iosBundleId: 'com.example.coba1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3XoClCSaOAB4w55NyjvF9jHr9aUEYooo',
    appId: '1:1088495781038:ios:a0a11cd9a31d3990a3d93f',
    messagingSenderId: '1088495781038',
    projectId: 'prohill-pa',
    storageBucket: 'prohill-pa.firebasestorage.app',
    iosBundleId: 'com.example.coba1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZNj4jbDJpFlL8HPYT9RpykrBrqrPwVmc',
    appId: '1:1088495781038:web:f4d74deddbbcd9f8a3d93f',
    messagingSenderId: '1088495781038',
    projectId: 'prohill-pa',
    authDomain: 'prohill-pa.firebaseapp.com',
    storageBucket: 'prohill-pa.firebasestorage.app',
    measurementId: 'G-0H3XNDC8MM',
  );
}
